### ISSUE TITLE
Unable to Queue Troops

### ISSUE THREAD

**Issue by chrishubert** [CodeSlinger69/ClAsHbOt#8] opened 2015-05-24 16:58 UTC
I can't manage to get the Troops to be queued:

```
5/24/2015 11:45:48 PM Auto Snipe clicked
5/24/2015 11:45:52 PM AutoQueueTroops()
5/24/2015 11:45:52 PM OpenBarracksWindow()
5/24/2015 11:46:03 PM Auto Raid, Queue Troops failed - error finding available Barracks Button panel.
5/24/2015 11:46:13 PM AutoQueueTroops()
5/24/2015 11:46:13 PM OpenBarracksWindow()
5/24/2015 11:46:20 PM Auto Snipe clicked
5/24/2015 11:46:21 PM Auto Raid, Queue Troops failed - error finding available Barracks Button panel.
5/24/2015 11:48:09 PM Close clicked
5/24/2015 11:53:10 PM Char start/end 23/29 of 81
5/24/2015 11:53:10 PM Char start/end 32/38 of 81
5/24/2015 11:53:10 PM Char start/end 41/46 of 81
5/24/2015 11:53:10 PM Char start/end 53/57 of 81
5/24/2015 11:53:10 PM Char start/end 60/66 of 81
5/24/2015 11:53:10 PM Char start/end 70/76 of 81
5/24/2015 11:53:10 PM Char start/end -1/-1 of 81
5/24/2015 11:53:10 PM Char start/end 29/34 of 81
5/24/2015 11:53:10 PM Char start/end 37/43 of 81
5/24/2015 11:53:11 PM Char start/end 46/51 of 81
5/24/2015 11:53:11 PM Char start/end 59/59 of 81
5/24/2015 11:53:11 PM Char start/end 62/68 of 81
5/24/2015 11:53:11 PM Char start/end 72/78 of 81
5/24/2015 11:53:11 PM Char start/end -1/-1 of 81
5/24/2015 11:53:11 PM Char start/end 37/38 of 81
5/24/2015 11:53:11 PM Char start/end 41/48 of 81
5/24/2015 11:53:11 PM Char start/end 55/61 of 81
5/24/2015 11:53:11 PM Char start/end 64/71 of 81
5/24/2015 11:53:11 PM Char start/end 74/79 of 81
5/24/2015 11:53:11 PM Char start/end -1/-1 of 81
5/24/2015 11:53:11 PM Char start/end 36/40 of 59
5/24/2015 11:53:11 PM Char start/end 43/48 of 59
5/24/2015 11:53:11 PM Char start/end 51/56 of 59
5/24/2015 11:53:11 PM Char start/end -1/-1 of 59
5/24/2015 11:53:12 PM Char start/end 2/5 of 54
5/24/2015 11:53:12 PM Char start/end 7/14 of 54
5/24/2015 11:53:12 PM Char start/end 17/23 of 54
5/24/2015 11:53:12 PM Char start/end 26/33 of 54
5/24/2015 11:53:12 PM Char start/end -1/-1 of 54
5/24/2015 11:53:13 PM Auto Snipe clicked
5/24/2015 11:53:17 PM Char start/end 23/29 of 81
5/24/2015 11:53:17 PM Char start/end 32/38 of 81
5/24/2015 11:53:17 PM Char start/end 41/46 of 81
5/24/2015 11:53:17 PM Char start/end 53/57 of 81
5/24/2015 11:53:17 PM Char start/end 60/66 of 81
5/24/2015 11:53:17 PM Char start/end 70/76 of 81
5/24/2015 11:53:17 PM Char start/end -1/-1 of 81
5/24/2015 11:53:18 PM Char start/end 29/34 of 81
5/24/2015 11:53:18 PM Char start/end 37/43 of 81
5/24/2015 11:53:18 PM Char start/end 46/51 of 81
5/24/2015 11:53:18 PM Char start/end 59/59 of 81
5/24/2015 11:53:18 PM Char start/end 62/68 of 81
5/24/2015 11:53:18 PM Char start/end 72/78 of 81
5/24/2015 11:53:18 PM Char start/end -1/-1 of 81
5/24/2015 11:53:18 PM Char start/end 37/38 of 81
5/24/2015 11:53:18 PM Char start/end 41/48 of 81
5/24/2015 11:53:18 PM Char start/end 55/61 of 81
5/24/2015 11:53:18 PM Char start/end 64/71 of 81
5/24/2015 11:53:18 PM Char start/end 74/79 of 81
5/24/2015 11:53:18 PM Char start/end -1/-1 of 81
5/24/2015 11:53:19 PM Char start/end 36/40 of 59
5/24/2015 11:53:19 PM Char start/end 43/48 of 59
5/24/2015 11:53:19 PM Char start/end 51/56 of 59
5/24/2015 11:53:19 PM Char start/end -1/-1 of 59
5/24/2015 11:53:19 PM Char start/end 2/5 of 54
5/24/2015 11:53:19 PM Char start/end 7/14 of 54
5/24/2015 11:53:19 PM Char start/end 17/23 of 54
5/24/2015 11:53:20 PM Char start/end 26/33 of 54
5/24/2015 11:53:20 PM Char start/end -1/-1 of 54
5/24/2015 11:53:20 PM AutoQueueTroops()
5/24/2015 11:53:20 PM OpenBarracksWindow()
5/24/2015 11:53:32 PM Auto Raid, Queue Troops failed - error finding available Barracks Button panel.
5/24/2015 11:53:39 PM Char start/end 23/29 of 81
5/24/2015 11:53:39 PM Char start/end 32/38 of 81
5/24/2015 11:53:39 PM Char start/end 41/46 of 81
5/24/2015 11:53:39 PM Char start/end 53/57 of 81
5/24/2015 11:53:39 PM Char start/end 60/66 of 81
5/24/2015 11:53:39 PM Char start/end 70/76 of 81
5/24/2015 11:53:39 PM Char start/end -1/-1 of 81
5/24/2015 11:53:39 PM Char start/end 26/31 of 81
5/24/2015 11:53:39 PM Char start/end 34/40 of 81
5/24/2015 11:53:39 PM Char start/end 42/47 of 81
5/24/2015 11:53:39 PM Char start/end 54/59 of 81
5/24/2015 11:53:39 PM Char start/end 62/68 of 81
5/24/2015 11:53:39 PM Char start/end 71/78 of 81
5/24/2015 11:53:39 PM Char start/end -1/-1 of 81
5/24/2015 11:53:39 PM Char start/end 37/38 of 81
5/24/2015 11:53:39 PM Char start/end 41/48 of 81
5/24/2015 11:53:40 PM Char start/end 55/61 of 81
5/24/2015 11:53:40 PM Char start/end 64/71 of 81
5/24/2015 11:53:40 PM Char start/end 74/79 of 81
5/24/2015 11:53:40 PM Char start/end -1/-1 of 81
5/24/2015 11:53:40 PM Char start/end 36/40 of 59
5/24/2015 11:53:40 PM Char start/end 43/48 of 59
5/24/2015 11:53:40 PM Char start/end 51/56 of 59
5/24/2015 11:53:40 PM Char start/end -1/-1 of 59
5/24/2015 11:53:41 PM Char start/end 2/5 of 54
5/24/2015 11:53:41 PM Char start/end 7/14 of 54
5/24/2015 11:53:41 PM Char start/end 17/23 of 54
5/24/2015 11:53:41 PM Char start/end 26/33 of 54
5/24/2015 11:53:41 PM Char start/end -1/-1 of 54
5/24/2015 11:53:41 PM AutoQueueTroops()
5/24/2015 11:53:41 PM OpenBarracksWindow()
5/24/2015 11:53:50 PM Auto Raid, Queue Troops failed - error finding available Barracks Button panel.
5/24/2015 11:53:57 PM Char start/end 23/29 of 81
5/24/2015 11:53:57 PM Char start/end 32/38 of 81
5/24/2015 11:53:57 PM Char start/end 41/46 of 81
5/24/2015 11:53:57 PM Char start/end 53/57 of 81
5/24/2015 11:53:57 PM Char start/end 60/66 of 81
5/24/2015 11:53:57 PM Char start/end 70/76 of 81
5/24/2015 11:53:57 PM Char start/end -1/-1 of 81
5/24/2015 11:53:58 PM Char start/end 26/31 of 81
5/24/2015 11:53:58 PM Char start/end 34/40 of 81
5/24/2015 11:53:58 PM Char start/end 42/47 of 81
5/24/2015 11:53:58 PM Char start/end 54/59 of 81
5/24/2015 11:53:58 PM Char start/end 62/68 of 81
5/24/2015 11:53:58 PM Char start/end 71/78 of 81
5/24/2015 11:53:58 PM Char start/end -1/-1 of 81
5/24/2015 11:53:58 PM Char start/end 37/38 of 81
5/24/2015 11:53:58 PM Char start/end 41/48 of 81
5/24/2015 11:53:58 PM Char start/end 55/61 of 81
5/24/2015 11:53:58 PM Char start/end 64/71 of 81
5/24/2015 11:53:58 PM Char start/end 74/79 of 81
5/24/2015 11:53:58 PM Char start/end -1/-1 of 81
5/24/2015 11:53:58 PM Char start/end 36/40 of 59
5/24/2015 11:53:58 PM Char start/end 43/48 of 59
5/24/2015 11:53:58 PM Char start/end 51/56 of 59
5/24/2015 11:53:58 PM Char start/end -1/-1 of 59
5/24/2015 11:53:59 PM Char start/end 2/5 of 54
5/24/2015 11:53:59 PM Char start/end 7/14 of 54
5/24/2015 11:53:59 PM Char start/end 17/23 of 54
5/24/2015 11:53:59 PM Char start/end 26/33 of 54
5/24/2015 11:53:59 PM Char start/end -1/-1 of 54
5/24/2015 11:54:00 PM AutoQueueTroops()
5/24/2015 11:54:00 PM OpenBarracksWindow()
5/24/2015 11:54:04 PM Auto Snipe clicked
5/24/2015 11:54:08 PM Auto Raid, Queue Troops failed - error finding available Barracks Button panel.
```

Thanks!

**Comment by CodeSlinger69** [comment] 2015-05-26 13:53
Hey.  Can you email/PM me a .bmp (uncompressed) screenshot of your base, as well as the release/commit your are running?  You probably don't want to post your base details here - SC can flag you as a botter from your screen name in the shot.

**Comment by chrishubert** [comment] 2015-05-26 14:20
Good call, that was not a smart move indeed to put the screenshot..
I'll send that to you, thanks!

I'm running your latest commit.

**Comment by chrishubert** [comment] 2015-05-26 14:25
I don't think I can get your email from GitHub though, you can get the bmp file uncompressed there:
[link removed]

I'll remove the file once you got it.
Cheers!

**Comment by CodeSlinger69** [comment] 2015-05-26 15:14
Thanks, please remove the link.  I'll look at this in a bit and try to see what is going on.

**Comment by CodeSlinger69** [comment] 2015-05-26 21:10
This is due to the 4/30 CoC client update.  They moved some pixels around on me.  In fact, in RegionDefs.au3, I noted "x1, x2 might need to be adjusted after 2015-04-30 update".  The problem is that after you click on a barracks, there are 3 different places where the "sword"-train troops button might appear, depending if the barracks is upgradable or not, and some other factors.  My barracks are no longer upgradeable, so I was unable to test where the new pixels have moved to.

I've had it in the back of my mind that, rather than checking for individual pixels, I need to do an image search for the sword picture instead.  This will be more robust than keying on individual pixel colors, albeit slightly more CPU intensive.  This will however, make it more robust, especially with future updates.

I didn't have a need to fix this quite yet, but your problem has now inspired me to make it a priority.  It won't take too long, and I should have the fix committed by tonight.

There are, unfortunately, some other areas in the bot that could be robust-ified like this as well, but I'll address those later.

As a note, pixel color matching is CPU-fast, but also a quick and dirty development method.  The image searching takes a bit more effort.  FWIW, that is the reason it was coded this way.

**Comment by CodeSlinger69** [comment] 2015-05-27 03:22
Fixed in commit https://github.com/CodeSlinger69/ClAsHbOt/commit/ff99decddf80da73501415d75379196d8ccc38fc

**Closed as completed by CodeSlinger69** 2015-05-27 03:22 UTC
