### ISSUE TITLE
AutoIT has stopped Working

### ISSUE THREAD

**Issue by Omareddie** [CodeSlinger69/ClAsHbOt#39] opened 2015-12-18 10:52 UTC
![capture](https://cloud.githubusercontent.com/assets/16307260/11895284/7156fb88-a5b8-11e5-8833-25e48ddb2e27.JPG)

**Comment by chrishubert** [comment] 2015-12-18 15:25
Can you post the last entries of the log?
Can you reproduce?

**Comment by Omareddie** [comment] 2015-12-18 15:32
2015/12/18 6:47:52 PM Restarting BlueStacks.
2015/12/18 6:47:53 PM Launched BlueStacks, pid=8064
2015/12/18 6:47:54 PM BlueStacks started successfully.
2015/12/18 6:47:56 PM Setting Mouse Click Method = MouseClick
2015/12/18 6:47:56 PM Setting Mouse Deploy Troop Click Delay = 60
2015/12/18 6:47:56 PM Setting Mouse Donate Troop Click Delay = 250
2015/12/18 6:47:56 PM Setting AutoRaid End Delay = 0
2015/12/18 6:47:56 PM Setting AutoSnipe Notify Only = False
2015/12/18 6:47:56 PM Setting Interval Online Check = 15000
2015/12/18 6:47:56 PM Setting Interval Collect Loot = 180000
2015/12/18 6:47:56 PM Setting Interval Troop Training Check = 180000
2015/12/18 6:47:56 PM Setting Interval Pause Between Nexts = 2500
2015/12/18 6:48:39 PM Collect Loot clicked
2015/12/18 6:48:41 PM Donate Troops clicked
2015/12/18 6:48:53 PM Setting Mouse Click Method = MouseClick
2015/12/18 6:48:53 PM Setting Mouse Deploy Troop Click Delay = 60
2015/12/18 6:48:53 PM Setting Mouse Donate Troop Click Delay = 250
2015/12/18 6:48:53 PM Setting AutoRaid End Delay = 0
2015/12/18 6:48:53 PM Setting AutoSnipe Notify Only = False
2015/12/18 6:48:53 PM Setting Interval Online Check = 15000
2015/12/18 6:48:53 PM Setting Interval Collect Loot = 180000
2015/12/18 6:48:53 PM Setting Interval Troop Training Check = 180000
2015/12/18 6:48:53 PM Setting Interval Pause Between Nexts = 2500
2015/12/18 6:49:05 PM Setting Mouse Click Method = MouseClick
2015/12/18 6:49:05 PM Setting Mouse Deploy Troop Click Delay = 60
2015/12/18 6:49:05 PM Setting Mouse Donate Troop Click Delay = 250
2015/12/18 6:49:05 PM Setting AutoRaid End Delay = 0
2015/12/18 6:49:05 PM Setting AutoSnipe Notify Only = False
2015/12/18 6:49:05 PM Setting Interval Online Check = 15000
2015/12/18 6:49:05 PM Setting Interval Collect Loot = 180000
2015/12/18 6:49:05 PM Setting Interval Troop Training Check = 180000
2015/12/18 6:49:05 PM Setting Interval Pause Between Nexts = 2500
2015/12/18 6:50:05 PM Setting Mouse Click Method = MouseClick
2015/12/18 6:50:05 PM Setting Mouse Deploy Troop Click Delay = 60
2015/12/18 6:50:05 PM Setting Mouse Donate Troop Click Delay = 250
2015/12/18 6:50:05 PM Setting AutoRaid End Delay = 0
2015/12/18 6:50:05 PM Setting AutoSnipe Notify Only = False
2015/12/18 6:50:05 PM Setting Interval Online Check = 15000
2015/12/18 6:50:05 PM Setting Interval Collect Loot = 180000
2015/12/18 6:50:05 PM Setting Interval Troop Training Check = 180000
2015/12/18 6:50:05 PM Setting Interval Pause Between Nexts = 2500
2015/12/18 6:50:40 PM Setting Mouse Click Method = MouseClick
2015/12/18 6:50:40 PM Setting Mouse Deploy Troop Click Delay = 60
2015/12/18 6:50:40 PM Setting Mouse Donate Troop Click Delay = 250
2015/12/18 6:50:40 PM Setting AutoRaid End Delay = 0
2015/12/18 6:50:40 PM Setting AutoSnipe Notify Only = False
2015/12/18 6:50:40 PM Setting Interval Online Check = 15000
2015/12/18 6:50:40 PM Setting Interval Collect Loot = 180000
2015/12/18 6:50:40 PM Setting Interval Troop Training Check = 180000
2015/12/18 6:50:40 PM Setting Interval Pause Between Nexts = 2500

**Comment by Omareddie** [comment] 2015-12-19 06:45
2015/12/19 2:41:29 PM Restarting BlueStacks.
2015/12/19 2:41:52 PM Launched BlueStacks, pid=3520
2015/12/19 2:41:53 PM BlueStacks started successfully.
2015/12/19 2:41:55 PM Setting Mouse Click Method = MouseClick
2015/12/19 2:41:55 PM Setting Mouse Deploy Troop Click Delay = 60
2015/12/19 2:41:55 PM Setting Mouse Donate Troop Click Delay = 250
2015/12/19 2:41:55 PM Setting AutoRaid End Delay = 0
2015/12/19 2:41:55 PM Setting AutoSnipe Notify Only = False
2015/12/19 2:41:55 PM Setting Interval Online Check = 15000
2015/12/19 2:41:55 PM Setting Interval Collect Loot = 180000
2015/12/19 2:41:55 PM Setting Interval Troop Training Check = 180000
2015/12/19 2:41:55 PM Setting Interval Pause Between Nexts = 2500

**Comment by CodeSlinger69** [comment] 2015-12-23 12:49
Is this reproducible?

**Comment by Omareddie** [comment] 2015-12-25 03:15
how to reproduce?

**Comment by CodeSlinger69** [comment] 2015-12-26 02:40
What I mean is, can you make this happen whenever you want, or does it just happen randomly?  If you can outline the steps to make it happen, it makes it much easier for me to debug and fix.  If it is just random, then my chances of fixing this are very low, as I simply have no idea what is causing it to happen.

**Comment by Omareddie** [comment] 2015-12-27 12:27
it is random. but i'll try again

**Comment by Deangelo7TheBest** [comment] 2016-01-03 08:55
It happens in mine too, but only when it starts to train troops

**Comment by chrishubert** [comment] 2016-01-03 09:30
Yup, same here - seems like it's not the same as the original issue though..
This is my last entries, always before crashing:

```
1/3/2016 4:28:25 PM AutoQueueTroops()
1/3/2016 4:28:26 PM OpenArmyManagerWindow()
1/3/2016 4:28:27 PM FillBarracksStrategy0(), initial fill.
1/3/2016 4:28:28 PM Barracks 1 is showing full.
```

**Comment by CodeSlinger69** [comment] 2016-01-03 14:34
Deangelo, chris, thanks for the pointer to the train troops area for this, as it helped me track down the problem.  In a nutshell, I added an image for the Warden to the bot, and adjusted some of the code to account for it.  I didn't make the comprehensive adjustments required in other areas, unfortunately, and in some cases when the ImageMatch DLL was being called, it was being sent arrays with a null entry.  Since the DLL generated an error, AutoIt force closed.

I've corrected this regression in commit https://github.com/CodeSlinger69/ClAsHbOt/commit/c40ab8e148ea52eb5fa5628cadfeb4d9eb847b7b, and tested that it works correctly now.

Sorry about that.  I'll close this issue in a few days if you guys don't see it happen again.

**Comment by Deangelo7TheBest** [comment] 2016-01-04 01:01
Thanks!

**Comment by chrishubert** [comment] 2016-01-04 01:23
Yep, It's fixed as well on my side.
Thanks @CodeSlinger69 !

**Comment by CodeSlinger69** [comment] 2016-01-05 13:35
Closing as this appears to be resolved.

**Closed as completed by CodeSlinger69** 2016-01-05 13:35 UTC
