### ISSUE TITLE
Feature request: Disconnect detector

### ISSUE THREAD

**Issue by synicalkid** [CodeSlinger69/ClAsHbOt#36] opened 2015-12-13 21:23 UTC
Long time user of pokubot. Now switching to ClAsHbOt. Quite happy with it. I'm used to the disconnect detector. The ol' "you've been online too long and your troops need to rest". pokubot would automatically keep trying to sign you back on. Someone correct me if I've just missed a checkbox somewhere.

**Comment by CodeSlinger69** [comment] 2015-12-13 21:25
ClAsHbOt already does this. Tick the "Keep Online" box.

**Comment by synicalkid** [comment] 2015-12-13 21:27
Hm. Ok, I do have that box checked however. It doesn't appear to be working. I was stuck on that screen until I manually clicked to sign back on.

**Comment by theBeastGPC** [comment] 2015-12-13 21:30
Same for me or when it loses connection I need to manually go back in

**Comment by synicalkid** [comment] 2015-12-13 21:48
![capture](https://cloud.githubusercontent.com/assets/16280554/11769593/5f2465ca-a1b9-11e5-8a0b-d4123df52c81.PNG)

This is new as well.

**Comment by CodeSlinger69** [comment] 2015-12-13 21:51
Are you guys using the new code, or downloading the last "Release"?  If the former, then please provide a screenshot when the bot gets stuck, along with the relevant sections of the log.  It currently detects both types of Android messages like the screenshot above...make sure you give it a minute or two to do something though - it only checks for those messages every 15 seconds by default, but might be longer if it was in the middle of doing something else and has to wait for a timeout.

**Comment by theBeastGPC** [comment] 2015-12-13 21:54
Nah mines not on the 3 hour personal break ...mine is when I lose
connection ...I had this before ...don't mind the loss of connection but of
the bot can auto press reconnect that would be great...I can get logs when
it next happens

**Comment by synicalkid** [comment] 2015-12-13 21:56
Brand new code pulled from master.zip. Waiting 5+mins to see if it would do anything before posting here.

![capture2](https://cloud.githubusercontent.com/assets/16280554/11769628/51d8a6e6-a1ba-11e5-9518-8a17e7d80e7b.PNG)

Not sure how to pull logs but I can if instructed.

**Comment by CodeSlinger69** [comment] 2015-12-13 22:14
Huh.  Maybe there is a third type of message that I have not accounted for, let me keep an eye out for this specific one. In the meantime, the log can be found in the "ClAsHboT Script" folder, file is "ClashBotLog.txt".

Does the bot detect and handle the other types of Android messages?

Also, can you attach the screenshots to your posts here?  I think GitHub is converting them to png.  If you can attach them as a .bmp it will help me diagnose the problem.  Not sure if GitHub can do that or not though.

**Comment by synicalkid** [comment] 2015-12-14 00:40
(when trying to upload bmp) Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

[clashbotlog.txt](https://github.com/CodeSlinger69/ClAsHbOt/files/60681/clashbotlog.txt)

log attached

**Comment by CodeSlinger69** [comment] 2015-12-14 01:45
Ya, its stuck.  I'll keep looking for that Break Extended message and see what's up.  You could always zip your .bmp screenshot, then attach it.

**Comment by CodeSlinger69** [comment] 2015-12-14 01:54
Well, I just saw that message popup, and while the bot does recognize that popup in normal situations, you seem to have discovered a bug where the bot does NOT do anything about it, if it is in the middle of doing something else.  In this case, from your log, the bot was trying to open the Army Manager window, it recognized that action failed, and tried to reset to the main screen.  But, it didn't recognize the Android popup as the current state.

I would think this is a fairly rare situation, as I hadn't seen it before this, and though I have tried to catch all the cases where an action might fail, and then reset to a known good state, apparently this one fell through the cracks.

Regardless, I have made a commit (https://github.com/CodeSlinger69/ClAsHbOt/commit/f9a89b33d91df654bf429fe2d838a73cac4890ed), that hopefully fixes this particular sequence of events.  I can't really test it, as I can't reproduce it, but I have good confidence that this is handled now.  Please let me know what you see.

**Comment by synicalkid** [comment] 2015-12-14 02:28
Sweet. I'll keep testing it out and report back my findings. Thanks for the quick push!

**Comment by synicalkid** [comment] 2015-12-14 02:53
Stuck again.

![capture](https://cloud.githubusercontent.com/assets/16280554/11771834/b6131172-a1e3-11e5-81cb-b7cb00fa643c.JPG)

[clashbotlog.txt](https://github.com/CodeSlinger69/ClAsHbOt/files/60760/clashbotlog.txt)

This time it was the new "you are kicked off because you didn't get a shield during your break".

**Comment by SupermansZ24** [comment] 2015-12-14 02:57
Off-topic but can someone upload a .reg file of the new resolution to use with the latest master release?

**Comment by synicalkid** [comment] 2015-12-14 03:20
Stuck on this screen now. 

![capture](https://cloud.githubusercontent.com/assets/16280554/11772159/8b04f2e4-a1e7-11e5-9baf-3ec6b2ee6ef6.JPG)

[clashbotlog.txt](https://github.com/CodeSlinger69/ClAsHbOt/files/60784/clashbotlog.txt)

**Comment by CodeSlinger69** [comment] 2015-12-14 03:24
Damn.  I need more debug code.  It still keeps getting stuck in AutoQueueTroops, which I have never seen before.

I've committed a new screen.au3, which should hopefully provide me with some more diagnostics.  Thanks for your patience with this.  https://github.com/CodeSlinger69/ClAsHbOt/commit/dd6dab4e90a8fd41f5770ac3374e00ecfb1e0c60

**Comment by synicalkid** [comment] 2015-12-14 03:25
![capture1](https://cloud.githubusercontent.com/assets/16280554/11772221/2a9d76be-a1e8-11e5-80ff-c1438c8312c8.JPG)

This is new as well. I'm testing now by click the - button and seeing if it will kick me off again in the sameish amount of time as it did before. 

This may be the new way supercell is detecting people botting and punishing them.

**Comment by CodeSlinger69** [comment] 2015-12-14 03:26
Just to verify, synical, you are using the required version of BlueStacks, right? https://github.com/CodeSlinger69/ClAsHbOt/wiki/Install

**Comment by synicalkid** [comment] 2015-12-14 03:38
Damn. I had 0.9.30. Re-downloading correct version and trying again.

**Comment by CodeSlinger69** [comment] 2015-12-14 03:47
That could do it.  Different versions of BlueStacks are enough to shift colors (different rendering in different versions of Android) and thus affect the bot's operation.

**Comment by synicalkid** [comment] 2015-12-14 04:06
Correct version installed. Resuming testing.

**Comment by synicalkid** [comment] 2015-12-14 14:42
Same problem with correct version of Bluestacks. Log attached.
[clashbotlog.txt](https://github.com/CodeSlinger69/ClAsHbOt/files/61308/clashbotlog.txt)

**Comment by CodeSlinger69** [comment] 2015-12-14 15:15
Can you attach a zipped up .bmp screenshot, please?

**Comment by synicalkid** [comment] 2015-12-14 15:16
Next time it blows up, I will do that. So far it hasn't, yet.

**Comment by synicalkid** [comment] 2015-12-14 22:32
Lost power in my house today. Back online grinding now though. Hope to be able to provide screenshots for you. It did do it again though, although I wasn't able to screencap. It gave me the "you've been online for too long". Then booted me. I reconnected manually, it booted me again after my new "guard" thing was done saying I was online too long and didn't get a shield when I was offline. The second time it booted me off, I got a "connection reset". When I manually attempted to reconnect, I got the, "your time has been extended because" no one attacked me. 

I'm trying to attach the .zip here to this comment however, github is telling me that it doesn't like that file type. Even though it's actually a .zip (ugh!)

I'll put the .zip here: https://dl.dropboxusercontent.com/u/34088557/screenshot.zip

**Comment by CodeSlinger69** [comment] 2015-12-14 23:48
synical, there is something radically different about your BlueStacks, and I don't know what it is.  This has happened at least once before...another guy just couldn't get it setup right and had very similar issues.

A couple things jump out about the screenshot:
1. Fuzzy text - usually this is very crisp, but if you look closely, you can see artifacts that almost look like jpg compression
2. The color of the horizontal blue bar - this is what the bot keys off of in order to determine if a popup is onscreen.  In regiondefs.au3, you can see these popups defined as $rAndroidMessageButton1 and $rAndroidMessageButton2.  The bot is looking for that bar to be color 0x33b5e5, but yours is  0x4daad3.
3. That blue bar on my BlueStacks is 2 pixels high...yours is 4 pixels high, with a darker blue shade row of pixels above and below.

It looks like you might be running on Win 10, given the window decoration.  Other people are running on Win 10, so I don't think that is the issue.

As long as you followed the installation instructions exactly as in the Wiki page, I really don't know what to do from here.  I never solved that other guy's problem either.  There must be some configuration thing that is making your BlueStacks act all wonky like this, but for the life of me, I have no idea what it might be.

P.S. Use a program called AutoIt Window Info to see the colors on your own computer.  It comes with the AutoIt install that you did.

**Comment by synicalkid** [comment] 2015-12-14 23:54
Screenshots are done via vnc hence the fuzzy text and off colors. They do
look perfect and crisp if I hookup a monitor to the actual box it is
running on.

**Comment by CodeSlinger69** [comment] 2015-12-15 01:33
Ah.  Can you get me clean screen shots then?  The bot's whole operating mechanism depends on accurate and consistent screen scraping, so I can't diagnose problems with fuzzy images.

**Comment by synicalkid** [comment] 2015-12-15 03:04
Understood. I'll work on them.

**Comment by CodeSlinger69** [comment] 2016-01-04 18:16
Closing due to inactivity.

**Closed as completed by CodeSlinger69** 2016-01-04 18:16 UTC
